import type { Metadata } from 'next';
import './globals.css';
import { anton, lato } from '@/utils/fonts';
import { NuqsAdapter } from 'nuqs/adapters/next';
import { LocalStorageProvider } from '@/lib/context/LocalStorageContext';
import { Header } from '@/components/Header';

export const metadata: Metadata = {
  title: 'JustWatch - The Streaming Guide',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico'
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${anton} ${lato} antialiased font-lato`}>
        <LocalStorageProvider>
          <NuqsAdapter>
            <Header />
            {children}
          </NuqsAdapter>
        </LocalStorageProvider>
      </body>
    </html>
  );
}
